"""Stable launchers for external Agents using the packaged Caddie runtime."""
from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path


def is_packaged() -> bool:
    return bool(getattr(sys, "frozen", False))


def _unix_launcher_script(mode: str, current_executable: Path) -> str:
    transport = "mcp" if mode == "--mcp" else "cli"
    fallback = shlex.quote(str(current_executable))
    forwarded = "" if mode == "--mcp" else ' "$@"'
    return f'''#!/bin/zsh
set -eu

# Stable entry point generated by Caddie. It uses Caddie's bundled runtime;
# no system Python or project virtual environment is required.
for candidate in \
  "${{CADDIE_EXECUTABLE:-}}" \
  "/Applications/Caddie.app/Contents/MacOS/Caddie" \
  "$HOME/Applications/Caddie.app/Contents/MacOS/Caddie" \
  {fallback}; do
  if [ -n "$candidate" ] && [ -x "$candidate" ]; then
    export CADDIE_EXTERNAL_TRANSPORT={transport}
    exec "$candidate" {mode}{forwarded}
  fi
done

echo "Caddie runtime not found. Install Caddie.app in Applications, then reopen it once." >&2
exit 127
'''


def _windows_launcher_script(mode: str, current_executable: Path) -> str:
    transport = "mcp" if mode == "--mcp" else "cli"
    forwarded = "" if mode == "--mcp" else " %*"
    fallback = str(current_executable)
    return rf'''@echo off
setlocal
set "CADDIE_EXTERNAL_TRANSPORT={transport}"

if defined CADDIE_EXECUTABLE if exist "%CADDIE_EXECUTABLE%" (
  "%CADDIE_EXECUTABLE%" {mode}{forwarded}
  exit /b %errorlevel%
)
if exist "%LOCALAPPDATA%\Programs\Caddie\Caddie.exe" (
  "%LOCALAPPDATA%\Programs\Caddie\Caddie.exe" {mode}{forwarded}
  exit /b %errorlevel%
)
if exist "%ProgramFiles%\Caddie\Caddie.exe" (
  "%ProgramFiles%\Caddie\Caddie.exe" {mode}{forwarded}
  exit /b %errorlevel%
)
if exist "{fallback}" (
  "{fallback}" {mode}{forwarded}
  exit /b %errorlevel%
)

echo Caddie runtime not found. Open Caddie.exe once, then reconnect the Agent. 1>&2
exit /b 127
'''


def ensure_packaged_launchers(
    home: Path | None = None,
    executable: Path | None = None,
    platform_name: str | None = None,
) -> dict[str, Path]:
    """Create stable MCP/CLI commands backed by the frozen app executable."""
    root = home or Path.home()
    runtime = executable or Path(sys.executable)
    platform = platform_name or os.name
    windows = platform == "nt"
    bin_dir = root / ".caddie" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    suffix = ".cmd" if windows else ""
    launchers = {
        "mcp": bin_dir / f"caddie-mcp{suffix}",
        "cli": bin_dir / f"caddie-agent{suffix}",
    }
    for key, path in launchers.items():
        mode = "--mcp" if key == "mcp" else "--agent-cli"
        content = (
            _windows_launcher_script(mode, runtime)
            if windows else _unix_launcher_script(mode, runtime)
        )
        try:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
        except OSError:
            current = ""
        if current != content:
            temp = path.with_suffix(".tmp")
            temp.write_text(content, encoding="utf-8")
            if not windows:
                os.chmod(temp, 0o755)
            temp.replace(path)
        elif not windows:
            os.chmod(path, 0o755)
    return launchers
