"""Stable launchers for external Agents using the packaged Caddie runtime."""
from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path


def is_packaged() -> bool:
    return bool(getattr(sys, "frozen", False))


def _launcher_script(mode: str, current_executable: Path) -> str:
    transport = "mcp" if mode == "--mcp" else "cli"
    fallback = shlex.quote(str(current_executable))
    forwarded = "" if mode == "--mcp" else ' "$@"'
    return f'''#!/bin/zsh
set -eu

# Stable entry point generated by Caddie. It uses Caddie's bundled runtime;
# no system Python or project virtual environment is required.
for candidate in \
  "${{CADDIE_EXECUTABLE:-}}" \
  "/Applications/Caddie Hosted Alpha.app/Contents/MacOS/Caddie Hosted Alpha" \
  "$HOME/Applications/Caddie Hosted Alpha.app/Contents/MacOS/Caddie Hosted Alpha" \
  {fallback}; do
  if [ -n "$candidate" ] && [ -x "$candidate" ]; then
    export CADDIE_EXTERNAL_TRANSPORT={transport}
    exec "$candidate" {mode}{forwarded}
  fi
done

echo "Caddie Hosted Alpha runtime not found. Install the app, then reopen it once." >&2
exit 127
'''


def ensure_packaged_launchers(
    home: Path | None = None,
    executable: Path | None = None,
) -> dict[str, Path]:
    """Create stable MCP/CLI commands backed by the frozen app executable."""
    root = home or Path.home()
    runtime = executable or Path(sys.executable)
    bin_dir = root / ".caddie-hosted-alpha" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    launchers = {
        "mcp": bin_dir / "caddie-hosted-alpha-mcp",
        "cli": bin_dir / "caddie-hosted-alpha-agent",
    }
    for key, path in launchers.items():
        mode = "--mcp" if key == "mcp" else "--agent-cli"
        content = _launcher_script(mode, runtime)
        try:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
        except OSError:
            current = ""
        if current != content:
            temp = path.with_suffix(".tmp")
            temp.write_text(content, encoding="utf-8")
            os.chmod(temp, 0o755)
            temp.replace(path)
        else:
            os.chmod(path, 0o755)
    return launchers
